/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package yaocr.view;

import yaocr.Learning;
import yaocr.Testing;
import yaocr.control.AnalyzeControl;
import yaocr.control.AnalyzeTestControl;
import yaocr.model.ImageManager;

import javax.swing.*;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Nicolas DELSAUT
 */
public class PanelAnalyze extends javax.swing.JPanel implements Observer {

    private ImageManager im;
    private JButton[] buttons = new JButton[10];

    /**
     * Creates new form PanelAnalyze
     */
    public PanelAnalyze(ImageManager im, Learning learning, Testing testing) {
        this.im = im;
        initComponents();
        jButtonAnalyze.addActionListener(new AnalyzeControl(im, learning));
        jButtonTests.addActionListener(new AnalyzeTestControl(testing));
        im.addObserver(this);
        
        buttons[0] = jButton0;
        buttons[1] = jButton1;
        buttons[2] = jButton2;
        buttons[3] = jButton3;
        buttons[4] = jButton4;
        buttons[5] = jButton5;
        buttons[6] = jButton6;
        buttons[7] = jButton7;
        buttons[8] = jButton8;
        buttons[9] = jButton9;
    }

    @Override
    public void update(Observable observable, Object o) {
        for(int i = 0; i < buttons.length; i++){
            buttons[i].setEnabled(true);
        }
        if(im.getCurrentNumber() != -1)
            buttons[im.getCurrentNumber()].setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonAnalyze = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonTests = new javax.swing.JButton();

        jButton7.setText("7");
        jButton7.setMaximumSize(new java.awt.Dimension(20, 10));
        jButton7.setMinimumSize(new java.awt.Dimension(20, 10));
        jButton7.setPreferredSize(new java.awt.Dimension(20, 10));

        jButton8.setText("8");
        jButton8.setMaximumSize(new java.awt.Dimension(20, 10));
        jButton8.setMinimumSize(new java.awt.Dimension(20, 10));
        jButton8.setPreferredSize(new java.awt.Dimension(20, 10));

        jButton9.setText("9");
        jButton9.setMaximumSize(new java.awt.Dimension(20, 10));
        jButton9.setMinimumSize(new java.awt.Dimension(20, 10));
        jButton9.setPreferredSize(new java.awt.Dimension(20, 10));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton4.setText("4");
        jButton4.setMaximumSize(new java.awt.Dimension(20, 10));
        jButton4.setMinimumSize(new java.awt.Dimension(20, 10));
        jButton4.setPreferredSize(new java.awt.Dimension(20, 10));

        jButton6.setText("6");
        jButton6.setMaximumSize(new java.awt.Dimension(20, 10));
        jButton6.setMinimumSize(new java.awt.Dimension(20, 10));
        jButton6.setPreferredSize(new java.awt.Dimension(20, 10));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setText("5");
        jButton5.setMaximumSize(new java.awt.Dimension(20, 10));
        jButton5.setMinimumSize(new java.awt.Dimension(20, 10));
        jButton5.setPreferredSize(new java.awt.Dimension(20, 10));

        jButton1.setText("1");
        jButton1.setMaximumSize(new java.awt.Dimension(20, 10));
        jButton1.setMinimumSize(new java.awt.Dimension(20, 10));
        jButton1.setPreferredSize(new java.awt.Dimension(20, 10));

        jButton3.setText("3");
        jButton3.setMaximumSize(new java.awt.Dimension(20, 10));
        jButton3.setMinimumSize(new java.awt.Dimension(20, 10));
        jButton3.setPreferredSize(new java.awt.Dimension(20, 10));

        jButton2.setText("2");
        jButton2.setMaximumSize(new java.awt.Dimension(20, 10));
        jButton2.setMinimumSize(new java.awt.Dimension(20, 10));
        jButton2.setPreferredSize(new java.awt.Dimension(20, 10));

        jButton0.setText("0");
        jButton0.setMaximumSize(new java.awt.Dimension(20, 10));
        jButton0.setMinimumSize(new java.awt.Dimension(20, 10));
        jButton0.setPreferredSize(new java.awt.Dimension(20, 10));

        jButtonAnalyze.setText("Analyze !");

        jButtonTests.setText("Analyze Test Files");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButtonAnalyze)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTests)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnalyze)
                    .addComponent(jButtonTests))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAnalyze;
    private javax.swing.JButton jButtonTests;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
