/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package yaocr.view;

import java.awt.Color;
import java.awt.GridLayout;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JPanel;
import yaocr.control.GridPanelControl;
import yaocr.model.ImageManager;
import yaocr.Image;

/**
 *
 * @author Nicolas DELSAUT
 */
public class PanelGrid extends javax.swing.JPanel implements Observer {

    private ImageManager modele;
    private JPanel[] tabJPanel = new JPanel[784];

    /**
     * Creates new form PanelGrid
     */
    public PanelGrid() {
        initComponents();
    }

    public PanelGrid(ImageManager mod) {
        initComponents();
        //Layout de type grid 28 par 28 pour simuler l'image
        this.setLayout(new GridLayout(28, 28));
        
        //Pattern MVC
        mod.addObserver(this);
        
        for(int i = 0 ; i < 28*28 ; ++i){
            //Un Jpanel pour chaque pixel
            JPanel p = new JPanel(); 
            //Un listener pour chaque pixel
            p.addMouseListener(new GridPanelControl(i, mod));
            //On garde le pointeur du JPanel et on l'ajoute à PanelGrid
            tabJPanel[i] = p;
            this.add(p);
        }
        
        modele = mod;
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        //On récupère l'image courante
        Image im = modele.getCurrentImage();
        for(int i = 0 ; i < 784 ; ++i){
            //On modifie la couleur de chaque panel en fonction du pixel
            tabJPanel[i].setBackground(new Color(im.getPixels()[i], 
                    im.getPixels()[i], im.getPixels()[i]));
            
        }
        //On repaint le composant
        repaint();
    }
}
