/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package yaocr.view;

import java.awt.CardLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import yaocr.Learning;

/**
 *
 * @author Nicolas DELSAUT
 */
public class PanelCardParamConsole extends javax.swing.JPanel {

    private JTextArea jta;
    private JScrollPane jScrollPane1;
    private PanelParam panelParam;
    
    /**
     * Creates new form PanelCardParamConsole
     */
    public PanelCardParamConsole() {
        initComponents();
        this.setLayout(new CardLayout());
        
        JPanel panelConsole = new JPanel();
        panelParam = new PanelParam();
        
        jta = new JTextArea();
        jta.setColumns(20);
        jta.setRows(6);
        jta.setSize(30, 30);
        jScrollPane1 = new JScrollPane(jta);
        panelConsole.add(jScrollPane1);
        
        JButton test = new JButton();
        panelParam.add(test);
        
        
        this.add(panelParam);
        this.add(panelConsole);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    void addingText(String string) {
        jta.setText(jta.getText() + string);
        jta.setCaretPosition(jta.getDocument().getLength());
    }

    void setParam(Learning learning) {
        panelParam.setParam(learning);
    }
}
